// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ZigitTest.Data;

#nullable disable

namespace ZigitTest.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20241214175107_adding email provaider")]
    partial class addingemailprovaider
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ZigitTest.Models.EmailProvider", b =>
                {
                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Name");

                    b.ToTable("EmailProviders");

                    b.HasData(
                        new
                        {
                            Name = "gmail"
                        },
                        new
                        {
                            Name = "yahoo"
                        },
                        new
                        {
                            Name = "hotmail"
                        });
                });

            modelBuilder.Entity("ZigitTest.Models.UserModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmailProviderName")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("EmailProviderName");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("ZigitTest.Models.UserModel", b =>
                {
                    b.HasOne("ZigitTest.Models.EmailProvider", "EmailProvider")
                        .WithMany()
                        .HasForeignKey("EmailProviderName");

                    b.Navigation("EmailProvider");
                });
#pragma warning restore 612, 618
        }
    }
}
